### ISSUE TITLE
pip install -e git+https://github.com/scikit-signal/pytftb#egg=tftb

### ISSUE THREAD

**Issue by rcox771** [scikit-signal/tftb#162]
^ this makes the install a bit quicker, but I'm not sure if it'll handle pip deps. As an alternative, you could move those to the setup.py? Just an idea.

-Russell

**Comment by jaidevd** [comment]
@rcox771 whoa... this is serious. I had no idea that `pip install -e` doesn't handle dependencies. I'll move them to setup.py.

Thanks a lot for pointing this out.

**Comment by jaidevd** [comment]
This should be fixed now. All requirements are in setup.py, using `pip install tftb` should work as expected. Please take a look, @rcox771 and let me know if this is still a problem.
